version: '2.1'

services:
  node:
    image: ghcr.io/wouterds/craftzing-slack-bot
    container_name: craftzing-slack-bot
    restart: unless-stopped
    mem_limit: 64mb
    env_file:
      - .env
    volumes:
      - ~/webcam.jpg:/avocado.jpg
      - ~/webcam2.jpg:/antwerpen.jpg
