name: code-review

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: "Node.js: setup"
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: "Node.js: install dependencies"
        run: yarn --frozen-lockfile

      - name: "Code: linting"
        run: yarn lint

      - name: "Code: tests"
        run: yarn test
